# fly.toml app configuration file
app = 'church-presentation-app-v2'
primary_region = 'hkg'  # Hong Kong - try this first

[build]

[env]
  FLASK_ENV = "production"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Simple HTTP health check
[[services.http_checks]]
  interval = "15s"
  grace_period = "10s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "5s"
  
[[services.tcp_checks]]
  interval = "15s"
  grace_period = "10s"
  timeout = "5s"