# fly.toml app configuration file
app = 'church-presentation-v1'
primary_region = 'nrt'

[build]

[env]
  # Set production environment
  FLASK_ENV = "production"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # Enable WebSocket support for SocketIO
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Health check for SocketIO apps
[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"
  restart_limit = 0
  timeout = "2s"